# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    GurobiOptimizer(;
        optimizer_type=nothing,
    )

    - optimizer_type::String
"""
Base.@kwdef mutable struct GurobiOptimizer <: OpenAPI.APIModel
    optimizer_type::Union{Nothing, String} = nothing

    function GurobiOptimizer(optimizer_type)
        OpenAPI.validate_property(GurobiOptimizer, Symbol("optimizer_type"), optimizer_type)
        return new(optimizer_type)
    end
end # type GurobiOptimizer

const _property_types_GurobiOptimizer =
    Dict{Symbol, String}(Symbol("optimizer_type") => "String")
OpenAPI.property_type(::Type{GurobiOptimizer}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_GurobiOptimizer[name]))}

function check_required(o::GurobiOptimizer)
    o.optimizer_type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{GurobiOptimizer}, name::Symbol, val) end
