# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    SimulationStatuses(;
        statuses=nothing,
    )

    - statuses::Vector{SimulationStatus}
"""
Base.@kwdef mutable struct SimulationStatuses <: OpenAPI.APIModel
    statuses::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{SimulationStatus} }

    function SimulationStatuses(statuses)
        OpenAPI.validate_property(SimulationStatuses, Symbol("statuses"), statuses)
        return new(statuses)
    end
end # type SimulationStatuses

const _property_types_SimulationStatuses =
    Dict{Symbol, String}(Symbol("statuses") => "Vector{SimulationStatus}")
OpenAPI.property_type(::Type{SimulationStatuses}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_SimulationStatuses[name]))}

function check_required(o::SimulationStatuses)
    o.statuses === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{SimulationStatuses}, name::Symbol, val) end
