# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    SimulationProgressEvent(;
        model_name=nothing,
        step=nothing,
        index=nothing,
        timestamp=nothing,
        wall_time=nothing,
        exec_time_s=nothing,
    )

    - model_name::String
    - step::Int64
    - index::Int64
    - timestamp::String
    - wall_time::String
    - exec_time_s::Float64
"""
Base.@kwdef mutable struct SimulationProgressEvent <: OpenAPI.APIModel
    model_name::Union{Nothing, String} = nothing
    step::Union{Nothing, Int64} = nothing
    index::Union{Nothing, Int64} = nothing
    timestamp::Union{Nothing, String} = nothing
    wall_time::Union{Nothing, String} = nothing
    exec_time_s::Union{Nothing, Float64} = nothing

    function SimulationProgressEvent(model_name, step, index, timestamp, wall_time, exec_time_s, )
        OpenAPI.validate_property(SimulationProgressEvent, Symbol("model_name"), model_name)
        OpenAPI.validate_property(SimulationProgressEvent, Symbol("step"), step)
        OpenAPI.validate_property(SimulationProgressEvent, Symbol("index"), index)
        OpenAPI.validate_property(SimulationProgressEvent, Symbol("timestamp"), timestamp)
        OpenAPI.validate_property(SimulationProgressEvent, Symbol("wall_time"), wall_time)
        OpenAPI.validate_property(SimulationProgressEvent, Symbol("exec_time_s"), exec_time_s)
        return new(model_name, step, index, timestamp, wall_time, exec_time_s, )
    end
end # type SimulationProgressEvent

const _property_types_SimulationProgressEvent = Dict{Symbol,String}(Symbol("model_name")=>"String", Symbol("step")=>"Int64", Symbol("index")=>"Int64", Symbol("timestamp")=>"String", Symbol("wall_time")=>"String", Symbol("exec_time_s")=>"Float64", )
OpenAPI.property_type(::Type{ SimulationProgressEvent }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_SimulationProgressEvent[name]))}

function check_required(o::SimulationProgressEvent)
    o.model_name === nothing && (return false)
    o.step === nothing && (return false)
    o.index === nothing && (return false)
    o.timestamp === nothing && (return false)
    o.wall_time === nothing && (return false)
    o.exec_time_s === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ SimulationProgressEvent }, name::Symbol, val)
end
