# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    CbcOptimizer(;
        optimizer_type=nothing,
    )

    - optimizer_type::String
"""
Base.@kwdef mutable struct CbcOptimizer <: OpenAPI.APIModel
    optimizer_type::Union{Nothing, String} = nothing

    function CbcOptimizer(optimizer_type)
        OpenAPI.validate_property(CbcOptimizer, Symbol("optimizer_type"), optimizer_type)
        return new(optimizer_type)
    end
end # type CbcOptimizer

const _property_types_CbcOptimizer =
    Dict{Symbol, String}(Symbol("optimizer_type") => "String")
OpenAPI.property_type(::Type{CbcOptimizer}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_CbcOptimizer[name]))}

function check_required(o::CbcOptimizer)
    o.optimizer_type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{CbcOptimizer}, name::Symbol, val) end
