# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    DeviceModel(;
        device_type=nothing,
        formulation=nothing,
    )

    - device_type::String
    - formulation::String
"""
Base.@kwdef mutable struct DeviceModel <: OpenAPI.APIModel
    device_type::Union{Nothing, String} = nothing
    formulation::Union{Nothing, String} = nothing

    function DeviceModel(device_type, formulation, )
        OpenAPI.validate_property(DeviceModel, Symbol("device_type"), device_type)
        OpenAPI.validate_property(DeviceModel, Symbol("formulation"), formulation)
        return new(device_type, formulation, )
    end
end # type DeviceModel

const _property_types_DeviceModel = Dict{Symbol,String}(Symbol("device_type")=>"String", Symbol("formulation")=>"String", )
OpenAPI.property_type(::Type{ DeviceModel }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_DeviceModel[name]))}

function check_required(o::DeviceModel)
    true
end

function OpenAPI.validate_property(::Type{ DeviceModel }, name::Symbol, val)
end
