# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    ListNamesResponse(;
        names=nothing,
    )

    - names::Vector{String}
"""
Base.@kwdef mutable struct ListNamesResponse <: OpenAPI.APIModel
    names::Union{Nothing, Vector{String}} = nothing

    function ListNamesResponse(names, )
        OpenAPI.validate_property(ListNamesResponse, Symbol("names"), names)
        return new(names, )
    end
end # type ListNamesResponse

const _property_types_ListNamesResponse = Dict{Symbol,String}(Symbol("names")=>"Vector{String}", )
OpenAPI.property_type(::Type{ ListNamesResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ListNamesResponse[name]))}

function check_required(o::ListNamesResponse)
    o.names === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ListNamesResponse }, name::Symbol, val)
end
