# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    SystemPath(;
        path=nothing,
        descriptor_type=nothing,
    )

    - path::String
    - descriptor_type::String
"""
Base.@kwdef mutable struct SystemPath <: OpenAPI.APIModel
    path::Union{Nothing, String} = nothing
    descriptor_type::Union{Nothing, String} = nothing

    function SystemPath(path, descriptor_type)
        OpenAPI.validate_property(SystemPath, Symbol("path"), path)
        OpenAPI.validate_property(SystemPath, Symbol("descriptor_type"), descriptor_type)
        return new(path, descriptor_type)
    end
end # type SystemPath

const _property_types_SystemPath =
    Dict{Symbol, String}(Symbol("path") => "String", Symbol("descriptor_type") => "String")
OpenAPI.property_type(::Type{SystemPath}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_SystemPath[name]))}

function check_required(o::SystemPath)
    o.path === nothing && (return false)
    o.descriptor_type === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{SystemPath}, name::Symbol, val) end
