# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    NetworkModel(;
        network_type=nothing,
        use_slacks=false,
        ptdf_matrix=nothing,
        duals=nothing,
    )

    - network_type::String
    - use_slacks::Bool
    - ptdf_matrix::String
    - duals::Vector{String}
"""
Base.@kwdef mutable struct NetworkModel <: OpenAPI.APIModel
    network_type::Union{Nothing, String} = nothing
    use_slacks::Union{Nothing, Bool} = false
    ptdf_matrix::Union{Nothing, String} = nothing
    duals::Union{Nothing, Vector{String}} = nothing

    function NetworkModel(network_type, use_slacks, ptdf_matrix, duals)
        OpenAPI.validate_property(NetworkModel, Symbol("network_type"), network_type)
        OpenAPI.validate_property(NetworkModel, Symbol("use_slacks"), use_slacks)
        OpenAPI.validate_property(NetworkModel, Symbol("ptdf_matrix"), ptdf_matrix)
        OpenAPI.validate_property(NetworkModel, Symbol("duals"), duals)
        return new(network_type, use_slacks, ptdf_matrix, duals)
    end
end # type NetworkModel

const _property_types_NetworkModel = Dict{Symbol, String}(
    Symbol("network_type") => "String",
    Symbol("use_slacks") => "Bool",
    Symbol("ptdf_matrix") => "String",
    Symbol("duals") => "Vector{String}",
)
OpenAPI.property_type(::Type{NetworkModel}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_NetworkModel[name]))}

function check_required(o::NetworkModel)
    true
end

function OpenAPI.validate_property(::Type{NetworkModel}, name::Symbol, val) end
