# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    SimulationModels(;
        decision_models=nothing,
    )

    - decision_models::Vector{DecisionModel}
"""
Base.@kwdef mutable struct SimulationModels <: OpenAPI.APIModel
    decision_models::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{DecisionModel} }

    function SimulationModels(decision_models)
        OpenAPI.validate_property(
            SimulationModels,
            Symbol("decision_models"),
            decision_models,
        )
        return new(decision_models)
    end
end # type SimulationModels

const _property_types_SimulationModels =
    Dict{Symbol, String}(Symbol("decision_models") => "Vector{DecisionModel}")
OpenAPI.property_type(::Type{SimulationModels}, name::Symbol) =
    Union{Nothing, eval(Base.Meta.parse(_property_types_SimulationModels[name]))}

function check_required(o::SimulationModels)
    o.decision_models === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{SimulationModels}, name::Symbol, val) end
