# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""
    StartSimulationResponse(;
        status=nothing,
    )

    - status::SimulationStatus
"""
Base.@kwdef mutable struct StartSimulationResponse <: OpenAPI.APIModel
    status = nothing # spec type: Union{ Nothing, SimulationStatus }

    function StartSimulationResponse(status, )
        OpenAPI.validate_property(StartSimulationResponse, Symbol("status"), status)
        return new(status, )
    end
end # type StartSimulationResponse

const _property_types_StartSimulationResponse = Dict{Symbol,String}(Symbol("status")=>"SimulationStatus", )
OpenAPI.property_type(::Type{ StartSimulationResponse }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_StartSimulationResponse[name]))}

function check_required(o::StartSimulationResponse)
    o.status === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ StartSimulationResponse }, name::Symbol, val)
end
