# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

@doc raw"""
    DecisionModelSystem(; value=nothing)
"""
mutable struct DecisionModelSystem <: OpenAPI.OneOfAPIModel
    value::Any # Union{ SystemCase, SystemPath }
    DecisionModelSystem() = new()
    DecisionModelSystem(value) = new(value)
end # type DecisionModelSystem

function OpenAPI.property_type(
    ::Type{DecisionModelSystem},
    name::Symbol,
    json::Dict{String, Any},
)
    discriminator = json["descriptor_type"]
    if discriminator == "SystemCase"
        return eval(Base.Meta.parse("SystemCase"))
    elseif discriminator == "SystemPath"
        return eval(Base.Meta.parse("SystemPath"))
    end
    throw(
        OpenAPI.ValidationException(
            "Invalid discriminator value: $discriminator for DecisionModelSystem",
        ),
    )
end
