# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.device_model import DeviceModel  # noqa: E501
from swagger_client.rest import ApiException


class TestDeviceModel(unittest.TestCase):
    """DeviceModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDeviceModel(self):
        """Test DeviceModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.device_model.DeviceModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
