# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.post_system_body import PostSystemBody  # noqa: E501
from swagger_client.rest import ApiException


class TestPostSystemBody(unittest.TestCase):
    """PostSystemBody unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPostSystemBody(self):
        """Test PostSystemBody"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.post_system_body.PostSystemBody()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
