# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.glpk_optimizer import GlpkOptimizer  # noqa: E501
from swagger_client.rest import ApiException


class TestGlpkOptimizer(unittest.TestCase):
    """GlpkOptimizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGlpkOptimizer(self):
        """Test GlpkOptimizer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.glpk_optimizer.GlpkOptimizer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
