# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.optimizer import Optimizer  # noqa: E501
from swagger_client.rest import ApiException


class TestOptimizer(unittest.TestCase):
    """Optimizer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOptimizer(self):
        """Test Optimizer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.optimizer.Optimizer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
