# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.feedforwards import Feedforwards  # noqa: E501
from swagger_client.rest import ApiException


class TestFeedforwards(unittest.TestCase):
    """Feedforwards unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testFeedforwards(self):
        """Test Feedforwards"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.feedforwards.Feedforwards()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
