# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.one_of_decision_model_system import OneOfDecisionModelSystem  # noqa: E501
from swagger_client.rest import ApiException


class TestOneOfDecisionModelSystem(unittest.TestCase):
    """OneOfDecisionModelSystem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOneOfDecisionModelSystem(self):
        """Test OneOfDecisionModelSystem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.one_of_decision_model_system.OneOfDecisionModelSystem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
