# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class DeviceModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'device_type': 'str',
        'formulation': 'str'
    }

    attribute_map = {
        'device_type': 'device_type',
        'formulation': 'formulation'
    }

    def __init__(self, device_type=None, formulation=None):  # noqa: E501
        """DeviceModel - a model defined in Swagger"""  # noqa: E501
        self._device_type = None
        self._formulation = None
        self.discriminator = None
        if device_type is not None:
            self.device_type = device_type
        if formulation is not None:
            self.formulation = formulation

    @property
    def device_type(self):
        """Gets the device_type of this DeviceModel.  # noqa: E501


        :return: The device_type of this DeviceModel.  # noqa: E501
        :rtype: str
        """
        return self._device_type

    @device_type.setter
    def device_type(self, device_type):
        """Sets the device_type of this DeviceModel.


        :param device_type: The device_type of this DeviceModel.  # noqa: E501
        :type: str
        """

        self._device_type = device_type

    @property
    def formulation(self):
        """Gets the formulation of this DeviceModel.  # noqa: E501


        :return: The formulation of this DeviceModel.  # noqa: E501
        :rtype: str
        """
        return self._formulation

    @formulation.setter
    def formulation(self, formulation):
        """Sets the formulation of this DeviceModel.


        :param formulation: The formulation of this DeviceModel.  # noqa: E501
        :type: str
        """

        self._formulation = formulation

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(DeviceModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DeviceModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
