# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class Feedforwards(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'model_name': 'str',
        'feedforwards': 'list[AbstractFeedforward]'
    }

    attribute_map = {
        'model_name': 'model_name',
        'feedforwards': 'feedforwards'
    }

    def __init__(self, model_name=None, feedforwards=None):  # noqa: E501
        """Feedforwards - a model defined in Swagger"""  # noqa: E501
        self._model_name = None
        self._feedforwards = None
        self.discriminator = None
        self.model_name = model_name
        self.feedforwards = feedforwards

    @property
    def model_name(self):
        """Gets the model_name of this Feedforwards.  # noqa: E501


        :return: The model_name of this Feedforwards.  # noqa: E501
        :rtype: str
        """
        return self._model_name

    @model_name.setter
    def model_name(self, model_name):
        """Sets the model_name of this Feedforwards.


        :param model_name: The model_name of this Feedforwards.  # noqa: E501
        :type: str
        """
        if model_name is None:
            raise ValueError("Invalid value for `model_name`, must not be `None`")  # noqa: E501

        self._model_name = model_name

    @property
    def feedforwards(self):
        """Gets the feedforwards of this Feedforwards.  # noqa: E501


        :return: The feedforwards of this Feedforwards.  # noqa: E501
        :rtype: list[AbstractFeedforward]
        """
        return self._feedforwards

    @feedforwards.setter
    def feedforwards(self, feedforwards):
        """Sets the feedforwards of this Feedforwards.


        :param feedforwards: The feedforwards of this Feedforwards.  # noqa: E501
        :type: list[AbstractFeedforward]
        """
        if feedforwards is None:
            raise ValueError("Invalid value for `feedforwards`, must not be `None`")  # noqa: E501

        self._feedforwards = feedforwards

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Feedforwards, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Feedforwards):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
