# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ProblemTemplate(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'network': 'NetworkModel',
        'devices': 'list[DeviceModel]',
        'services': 'list[ServiceModel]'
    }

    attribute_map = {
        'network': 'network',
        'devices': 'devices',
        'services': 'services'
    }

    def __init__(self, network=None, devices=None, services=None):  # noqa: E501
        """ProblemTemplate - a model defined in Swagger"""  # noqa: E501
        self._network = None
        self._devices = None
        self._services = None
        self.discriminator = None
        self.network = network
        if devices is not None:
            self.devices = devices
        if services is not None:
            self.services = services

    @property
    def network(self):
        """Gets the network of this ProblemTemplate.  # noqa: E501


        :return: The network of this ProblemTemplate.  # noqa: E501
        :rtype: NetworkModel
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this ProblemTemplate.


        :param network: The network of this ProblemTemplate.  # noqa: E501
        :type: NetworkModel
        """
        if network is None:
            raise ValueError("Invalid value for `network`, must not be `None`")  # noqa: E501

        self._network = network

    @property
    def devices(self):
        """Gets the devices of this ProblemTemplate.  # noqa: E501


        :return: The devices of this ProblemTemplate.  # noqa: E501
        :rtype: list[DeviceModel]
        """
        return self._devices

    @devices.setter
    def devices(self, devices):
        """Sets the devices of this ProblemTemplate.


        :param devices: The devices of this ProblemTemplate.  # noqa: E501
        :type: list[DeviceModel]
        """

        self._devices = devices

    @property
    def services(self):
        """Gets the services of this ProblemTemplate.  # noqa: E501


        :return: The services of this ProblemTemplate.  # noqa: E501
        :rtype: list[ServiceModel]
        """
        return self._services

    @services.setter
    def services(self, services):
        """Sets the services of this ProblemTemplate.


        :param services: The services of this ProblemTemplate.  # noqa: E501
        :type: list[ServiceModel]
        """

        self._services = services

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ProblemTemplate, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ProblemTemplate):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
