# coding: utf-8

"""
    SiennaOperationsSimulations

    This is a SiennaOperationsSimulations server.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class SimulationModels(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'decision_models': 'list[DecisionModel]'
    }

    attribute_map = {
        'decision_models': 'decision_models'
    }

    def __init__(self, decision_models=None):  # noqa: E501
        """SimulationModels - a model defined in Swagger"""  # noqa: E501
        self._decision_models = None
        self.discriminator = None
        self.decision_models = decision_models

    @property
    def decision_models(self):
        """Gets the decision_models of this SimulationModels.  # noqa: E501


        :return: The decision_models of this SimulationModels.  # noqa: E501
        :rtype: list[DecisionModel]
        """
        return self._decision_models

    @decision_models.setter
    def decision_models(self, decision_models):
        """Sets the decision_models of this SimulationModels.


        :param decision_models: The decision_models of this SimulationModels.  # noqa: E501
        :type: list[DecisionModel]
        """
        if decision_models is None:
            raise ValueError("Invalid value for `decision_models`, must not be `None`")  # noqa: E501

        self._decision_models = decision_models

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SimulationModels, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SimulationModels):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
